# my test


In [3]:
import numpy as np
my_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
def power_func(n):
    return lambda x : x ** n 
square_func = power_func(2)
cube_func = power_func(3)
square_func(my_arr), cube_func(my_arr)

(array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]),
 array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000]))

In [5]:
import pandas as pd
df = pd.DataFrame({'square': square_func(my_arr), 'cube': cube_func(my_arr)})
df

,square,cube
0,1,1
1,4,8
2,9,27
3,16,64
4,25,125
5,36,216
6,49,343
7,64,512
8,81,729
9,100,1000


In [ ]:
models = [
    {'make': 'Nokia', 'model': 216, 'color': 'Black'},
    {'make': 'Mi Max', 'model': '2', 'color': 'Gold'},
    {'make': 'Samsung', 'model': 7, 'color': 'Blue'},
]
print(models)
sorted_models = sorted(models, key=lambda x: x['color'])
print(sorted_models)

: 

In [ ]:
myfamily = {
    'child1': {
        'name': 'John',
        'age': 5
    },
    'child2': {
        'name': 'Jane',
        'age': 3
    },
    'child3': {
        'name': 'Doe',
        'age': 1
    }
}   

for x, obj in myfamily.items():
  print(x)

  for y in obj:
    print(y + ':', obj[y])


child1
name: John
age: 5
child2
name: Jane
age: 3
child3
name: Doe
age: 1


In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"{self.name}({self.age})"

p1 = Person("John", 36)

print(p1) 


: 

In [18]:
class Student:
    def __init__(self, student_id, student_name, student_age):
        self.student_id = student_id
        self.name = student_name
        self.age = student_age

student1 = Student('123456', 'Jane Doe', '21')
print(student1.__dict__)
print(student1.age, student1.name, student1.student_id)

{'student_id': '123456', 'name': 'Jane Doe', 'age': '21'}
21 Jane Doe 123456


In [23]:
import scipy.stats as stats
import numpy as np
class rv_histogram(stats.rv_continuous):
    def _pdf(self, x):
        return np.interp(x, self.x, self.y)

    def _cdf(self, x):
        return np.interp(x, self.x, self.cdf)
np.histogram(np.random.randn(1000), bins=30, density=True)

(array([0.00476754, 0.00953507, 0.01430261, 0.        , 0.02383769,
        0.05244291, 0.08104814, 0.10488582, 0.16209627, 0.15732873,
        0.21930672, 0.29081978, 0.36233284, 0.37663546, 0.31942501,
        0.40524068, 0.4338459 , 0.40047314, 0.25744702, 0.31942501,
        0.24314441, 0.12395597, 0.10488582, 0.12395597, 0.05244291,
        0.0381403 , 0.03337276, 0.01907015, 0.01907015, 0.01430261]),
 array([-3.25618301, -3.04643111, -2.83667922, -2.62692732, -2.41717543,
        -2.20742354, -1.99767164, -1.78791975, -1.57816786, -1.36841596,
        -1.15866407, -0.94891218, -0.73916028, -0.52940839, -0.3196565 ,
        -0.1099046 ,  0.09984729,  0.30959918,  0.51935108,  0.72910297,
         0.93885486,  1.14860676,  1.35835865,  1.56811054,  1.77786244,
         1.98761433,  2.19736623,  2.40711812,  2.61687001,  2.82662191,
         3.0363738 ]))

In [2]:
x = lambda a : a + 15
print(x(70))
def myfunc(x):
    return lambda y : y * x

hm = myfunc(x(70))
print(hm(2))

85
170


In [77]:
sample_grades = [('English', 88), ('Science', 90), ('Math', 97), ('Social sciences', 82)]
sample_grades.sort(key=lambda x: x[1])
print(sample_grades)

[('Social sciences', 82), ('English', 88), ('Science', 90), ('Math', 97)]


In [1]:
import numpy as np
x = 1.22*((5.5*10**-7)/8.4)
x*((3600*180)/np.pi)

0.016476629165690673